# Generated by Django 5.2.10 on 2026-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200, unique=True)),
                ('date_published', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('tldr_text', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('tile_image', models.URLField()),
                ('blog_image', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
    ]
