# Generated by Django 5.2.10 on 2026-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='date_published',
            field=models.DateField(),
        ),
    ]
