# Generated by Django 5.2.10 on 2026-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogitem_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='slug',
            field=models.SlugField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
